version: '3'

services:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: devcorp_db
    ports: 
      - 3306:3306
  web:
    build: .
    depends_on: 
      - db
    volumes: 
      - ./php/:/var/www/html/
    ports: 
      - 8000:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8100:80
    links: 
      - db:db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  ftpd_server:
      image: stilliard/pure-ftpd:hardened
      container_name: pure-ftpd
      ports:
          - "21:21"
          - "30000-30009:30000-30009"
      volumes:
          - "./data:/home/Tora/"
      environment: 
          PUBLICHOST: "192.168.2.49"
          FTP_USER_NAME: "Devcorp"
          FTP_USER_PASS: 1234
          FTP_USER_HOME: /home/Devcorp
      restart: always